project_name: todobi

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: todobi
    binary: todobi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: todobi
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: WillyV3
    name: todobi
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - repository:
      owner: WillyV3
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/WillyV3/todobi
    description: "Beautiful terminal task manager built with Bubble Tea"
    license: MIT
    install: |
      bin.install "todobi"
    test: |
      system "#{bin}/todobi", "version"
